# Generated by Django 5.1 on 2025-01-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='time',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('Heart', 'Heart Specialist'), ('Liver', 'Liver Specialist'), ('Skin', 'Dermatologist'), ('child and newborn', 'Pediatrician')], max_length=50),
        ),
    ]
